### ISSUE TITLE
ToDo 

### ISSUE THREAD

**Issue by wisharya** [wisharya/daily-logs#105]
- [x] IndiaFOSS expense
- [x] Outreach/Communication/Social-Media role define
- [x] Invite Jyotsna to FOSS meetup
- [x] IndiaFOSS App
- [x] Expense Claim
- [x] Close email threads
- [x] Monthly Meetups leads
- [x] Fix FOSS Pledge bug
- [x] IndiaFOSS Playbook
- [x] PeriFerry case study
