### ISSUE TITLE
ToDo: 12-17 Sept 2022

### ISSUE THREAD

**Issue by wisharya** [wisharya/daily-logs#113]
- [x] [Mon School] Schedule interview for Mon.School
- [x] Test IndiaFOSS app
- [x] [Accounts] Payment to Conf Video Editor
- [x] [Accounts] 12A activity and purchase invoice documentation
- [x] [Accounts] Payment to Takshashila
- [x] [Foundation] AWS SES setup - Reach out to Vishnu
- [x] #115
- [x] [FOSS Meetup] Speakers' announcements on social media
- [x] [FOSS Meetup] Add the agenda on the thread and announce
- [x] Issue with the ERP invoice system
- [x] Send RSVP confirmation email to Sept meetup participants
- [x] Write a newsletter to all participants sharing the pictures, talks, sponsors, thank-you notes and CTA for DelhiFOSS, KochiFOSS, Meetups, Mumbai Meetups etc
- [x] IndiaFOSS cookbook setup
