### ISSUE TITLE
ToDo - 07-10-22

### ISSUE THREAD

**Issue by wisharya** [wisharya/daily-logs#129]
- [x] #128 
- [x] FOSS Meetup reminder email
- [x] Go through public policy lectures
- [ ] #131
- [x] Look into the IndiaFOSS app
