### ISSUE TITLE
DelhiFOSS ToDo

### ISSUE THREAD

**Issue by wisharya** [wisharya/daily-logs#136]
- [x] Remove Yash from the speakers' list
- [x] Send a newsletter along with TG group link
- [ ] Reach out to engineering colleges in Delhi
- [ ] Ping people on Twitter
- [ ] Ping Prof. in engineering colleges
