### ISSUE TITLE
ToDo: IndiaFOSS 2.0

### ISSUE THREAD

**Issue by wisharya** [wisharya/daily-logs#79]
- [x] Speaker Announcement on the website and social media
- [ ] Newsletter for fu and monschool website users
- [x] Form to capture details of the conference pass for sponsors and community partners and tickets with multiple bookings.
